### ISSUE TITLE
Epic - Design feedback to 2.0

### ISSUE THREAD

**Issue by gazhands** [AusDTO/dto-design-guide#43]

**Comment by klepas** [comment]
Please review https://github.com/AusDTO/dto-design-guide/pull/44 :)

**Comment by gazhands** [comment]
My notes so far on design guide feedback
- [x] Can we update the header with the right logo
- [x] Make smaller -2 'DTA Design Guide' above page title and add section title
- [x] Fix navigation/side nav on mobile (collapsed)
- [x] Iterate on how we display a Component/Pattern 
  - Example in box only
  - Use of borders and colours in accordions  
  - Accordion states, open v closed
- [x] gaz to do a design of above
- [x] Update the homepage layout
- [x] Iterate on breadcrumbs, change background colour to white
- [x] Add version number of UI-Kit (design on homepage)

Cancelled:

- Foundation>colours page, Iterate on design — we agreed to revisit this page after the ‘2.0’ DG release
- Address type sizes used, headers vs body copy (Foundations>layout seems pretty close) — happy to do this within UI-Kit after the DG 2.0 release.

**Comment by joolswood** [comment]
> Address type sizes used, headers vs body copy (Foundations>layout seems pretty close)

Not sure exactly what is required here, please can you elaborate? Can we also look at overriding the H1 to make > than H2?

> Remove 'DTA Design Guide' above page title

I'd like to explore adding to / changing this to the section title (`Foundations`/`Components`/`Patterns`)?

>  Example in box only

Is this about putting the code into an accordion?

> Use of borders and colours in accordions

Agreed. Can we work on making the example boxes and accordions more harmonious.

> Iterate on breadcrumbs, Q. do we need them for the guide?

It'd suggest it's valuable for a user to see them in the context of a real site (ie. keep them). Although at the moment we appear to  use different colours from our rendered example.

**Comment by gazhands** [comment]
![design guide - home](https://cloud.githubusercontent.com/assets/17328069/20815686/fd8ea70e-b872-11e6-8af0-6a1f2296cf79.png)

**Comment by klepas** [comment]
@gazhands I shoulda mentioned this earlier (it occurred to me first when I did the content guide styling months back, which has a similar homepage design): we shouldn’t be styling the links to these sections as buttons. Are you alright if we preserve that design but opt for link styling instead?—happy to ofc. give them some extra embellishments over generic link styles.

**Comment by joolswood** [comment]
- [ ] Can we also take a look at the empty row in the footer? Or is this intentional?
![screen shot 2016-12-02 at 11 56 10 am](https://cloud.githubusercontent.com/assets/13774080/20819126/91b7216e-b886-11e6-9269-87a2561d38ad.png)

**Comment by gazhands** [comment]
We should look at footer, it needs some love

**Comment by gazhands** [comment]
![4 patterns example layout 2](https://cloud.githubusercontent.com/assets/17328069/20819216/0c185392-b887-11e6-913d-698ff32c9185.png)
![4 patterns example layout 1](https://cloud.githubusercontent.com/assets/17328069/20819217/0c45eaf0-b887-11e6-89f9-3ad154a91aa8.png)

**Comment by joolswood** [comment]
- [x] Also seems like a massive gap at top of pages?

![screen shot 2016-12-02 at 3 00 10 pm](https://cloud.githubusercontent.com/assets/13774080/20822626/3f207eae-b8a0-11e6-8c81-773943c17b5b.png)

**Comment by klepas** [comment]
> Also seems like a massive gap at top of pages?

Should be fixed by https://github.com/AusDTO/dto-design-guide/pull/50

**Comment by joolswood** [comment]
- [x] Please can we replace the hyphen in the breadcrumbs with a non breaking space @klepas or @dominikwilkowski ? ie `Home > Getting-started > Overview`

**Comment by klepas** [comment]
I reckon we should lift out the remaining to-dos after a chat with Gaz and Jools into a new ticket @dominikwilkowski @gazhands @joolswood ? :)

**Comment by klepas** [comment]
> - Can we also take a look at the empty row in the footer? Or is this intentional?

Intentional. Will run through it.

**Comment by klepas** [comment]
Hey @AusDTO/guides I’m keen to work through the remaining items here and get them split into their own new, more granular issues.

@gazhands can we do a hangout after standup tomorrow? :)

**Comment by gazhands** [comment]
I've captured the to remaining items (added to inbox)
1. Colour palette (68)
2. Type (69)

**Comment by gazhands** [comment]
3. Accordion appearance and states (70)

**Comment by klepas** [comment]
Thanks @gazhands.

Btw, you add a `#` in front of (either the PR *or* issue) number GitHub will auto-link it for us! (:
